### PR TITLE
ci(workflows): reusable workflows with superlinter and phpstan

### PR DESCRIPTION
**Pull request by AsifNawaz-cnic**

### CODE REVIEW

**Review by KaiSchwarz-cnic — CHANGES_REQUESTED** [review]
see my previous comments.
... sorry wrong PR. not related to this one.

**Comment by KaiSchwarz-cnic** [comment]
phew... not sure why I reviewed #108. please check if my comments made there affect this version as well and review accordingly.

ty!

**Comment by AsifNawaz-cnic** [comment]
> phew... not sure why I reviewed #108. please check if my comments made there affect this version as well and review accordingly.
> 
> ty!

Hi Kai,
I cannot see any comments on #108 pull request, I believe this must be related to #107 request.

**Comment by KaiSchwarz-cnic** [comment]
if the above leaves questions, just ask.

**Comment by AsifNawaz-cnic** [comment]
> if the above leaves questions, just ask. Now, I know it: in RSRMID-895 I clicked on the link provided to review without noticing it already being closed.

Okay I see, and I did not edited gulp this time and you are right I thought may be gulp composer update is related to phpstan codefix commands, I have reverted them in current pull request.

**Review by KaiSchwarz-cnic — APPROVED** [review]
ty

**Pull request merged**
